create table tags (
id int primary key generated by default as identity,
name varchar(255)
)

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  interests jsonb DEFAULT '[]'::jsonb,
  geoprofiles jsonb DEFAULT '[]'::jsonb,
  active_profile_id TEXT
);

CREATE TABLE events_cache (
    id INT PRIMARY KEY,
    title TEXT,
    place JSONB,
    start_date TIMESTAMP,
    end_date TIMESTAMP,
	tags TEXT[],
	thumbnail TEXT
);

CREATE TABLE events_archive (
    id INT PRIMARY KEY,
    title TEXT,
    place JSONB,
    dates JSONB,
	tags TEXT[],
	thumbnail TEXT
);

CREATE TABLE tracked_events (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  event_id INTEGER REFERENCES events_archive(id),
  UNIQUE(user_id, event_id)
);